export const GET_PICTURES_REQUEST = 'GET_PICTURES_REQUEST';
export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS';
export const GET_PICTURES_FAILURE = 'GET_PICTURES_FAILURE';
export const SET_UNIQ_ID = 'SET_UNIQ_ID';
export const DUPLICATE_PICTURES = 'DUPLICATE_PICTURES';
export const SHUFFLE_PICTURES = 'SHUFFLE_PICTURES';
export const UPLOAD_PICTURES = 'UPLOAD_PICTURES';
export const SHOW_PICTURES = 'SHOW_PICTURES';
